[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  NODE_ENV = "production"

[context.branch-deploy.environment]
  NODE_ENV = "development"

[context.deploy-preview.environment]
  NODE_ENV = "preview"
